### ISSUE TITLE
Well, this is embarrassing.

### ISSUE THREAD

**Issue by mailtruck** [mozilla/firefox-browser-architecture#21]
Where can I open an issue against the Firefox browser?

The message shown on crash recovery is troubling:

> Well, this is embarrassing

I see this message frequently after a hard reboot. Firefox shouldn't feel bad about the circumstances that could lead to the session restore screen.

Firefox should be more confident.
![embyrassing](https://user-images.githubusercontent.com/192746/29927545-aac6880a-8e34-11e7-847f-134ec2c619e3.png)

**Comment by mykmelez** [comment]
@mailtruck You can do so at https://bugzilla.mozilla.org/.
