### ISSUE TITLE
Make rectangular tabs optional

### ISSUE THREAD

**Issue by natewind** [mozilla/firefox-browser-architecture#42]
Please add an option to switch from these ugly rectagular tabs, to normal **rounded** trapezoids.
That’s not what I left Chrome for T_T

**Comment by natewind** [comment]
(Not sure though if it’s the right repository for this issue.)

**Comment by mykmelez** [comment]
> (Not sure though if it’s the right repository for this issue.)

This isn't the right forum for your Firefox feature request, which you can report via [this form on bugzilla.mozilla.org](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox).

**Comment by natewind** [comment]
Ok, thanks.
