### ISSUE TITLE
all Browser Architecture Update links in README.md/index.html are 404

### ISSUE THREAD

**Issue by skierpage** [mozilla/firefox-browser-architecture#59]
I found https://mozilla.github.io/firefox-browser-architecture/ . The Browser Architecture Update and Browser Architecture Newsletter #_N_ links in the **Posts** section are all 404s, e.g. [Browser Architecture Newsletter #5](https://mozilla.github.io/firefox-browser-architecture/posts/2017-11-29-browser-architecture-newsletter-5.md)

That index.html file seems to be [README.md](https://github.com/mozilla/firefox-browser-architecture/blob/master/README.md) in this repo, and the same links are broken here too.

I thought the problem is these posts are no longer in `posts` but in `newsletter/_posts`, however the link to "Browser Architecture Update" uses that path and is still a 404.

**Comment by joewalker** [comment]
Thanks for raising the issue. PR on it's way.

**Comment by sithutin1997** [comment]
Thank you for your effort. It really helps me alot.
