### ISSUE TITLE
Add *downloading speed and uploading speed meter* on the main window !

### ISSUE THREAD

**Issue by anubhavsinha98** [mozilla/firefox-browser-architecture#72]
This repository is for documentation about the Firefox Architectural Change program. It's not a place to raise bugs about Firefox itself.

* If you have found a bug in Firefox please start here: https://bugzilla.mozilla.org/enter_bug.cgi
* If you want to give broader feedback: https://input.mozilla.org/
* If you have a website that doesn't work properly in Firefox: https://webcompat.com/

**Comment by mykmelez** [comment]
@anubhavsinha98, this repository is for documentation about the Firefox Architectural Change program. It's not a place to raise bugs about Firefox itself. To request that Firefox add downloading and uploading speed meters to its main window, report a bug in the Firefox tracker:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox
