### ISSUE TITLE
ARM Windows support for Snapdragon 835 and upwards CPUs

### ISSUE THREAD

**Issue by drbree82** [mozilla/firefox-browser-architecture#73]
Need someone to attempt compilation of Firefox on ARM Windows Architecture.

**Comment by mykmelez** [comment]
This isn't the right place to solicit such a person. I'm not actually sure what the right place would be, as it isn't clear exactly what you're looking for, but perhaps the #introduction, #mozillians, or #newbies channels on IRC would be able to point you in the right direction, for which see https://wiki.mozilla.org/IRC. Alternately, perhaps there's a Discourse category that can help, for which see https://discourse.mozilla.org/.
