### ISSUE TITLE
"Own" the Project Specific Etiquette from the CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by joewalker** [mozilla/firefox-browser-architecture#78]
The [raw source to the CODE_OF_CONDUCT](https://raw.githubusercontent.com/mozilla/firefox-browser-architecture/master/CODE_OF_CONDUCT.md) contains:

``` html
<!--
## Project Specific Etiquette

In some cases, there will be additional project etiquette i.e.: (https://bugzilla.mozilla.org/page.cgi?id=etiquette.html).
Please update for your project.
-->
```

We should update that for this project.

At the same time, we should link from the README

**Comment by mykmelez** [comment]
Several of us discussed this today and concluded that this project doesn't need project-specific etiquette, as it isn't active enough to have needs beyond Mozilla's standard community participation guidelines.

@joewalker I'll leave this open in case you disagree or want to discuss further (and also to track referencing the Code of Conduct in the README).
