### ISSUE TITLE
[Feature Request] Lightshot editor functions in firefox screenshot plugin

### ISSUE THREAD

**Issue by kirantpatil** [mozilla/firefox-browser-architecture#79]
Hi,

Sorry, I could not find the firefox repository to create feature request.

[Lightshot editor](https://app.prntscr.com/en/index.html) has many feature which could be incorporated with firefox screenshot feature.

Thanks.

**Comment by joewalker** [comment]
Thanks for the issue. The screenshot feature has a repository here: https://github.com/mozilla-services/screenshots/issues
The Lightshot editor doesn't look like it's open source (although their website isn't clear on this) so it's not just a case of bundling this functionality, and I'm not sure that the screenshots team actually wants to add many new features, preferring a simple UI for now. However that's their call.

**Comment by kirantpatil** [comment]
Dear Joe,

Thanks a lot.
